services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: test-app
    build: .
    container_name: developer-app
    depends_on:
      - db
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    command: ["/bin/sh", "./docker-entrypoint.sh", "npm", "run", "start:prod"]

volumes:
  pgdata:
